### ISSUE TITLE
_getAuthCookie should be public function for set cookie previously

### ISSUE THREAD

**Issue by jsiesquen** [alvimm/vtex-cms-sauce#5]
Hello,

I just try execute saveFile() into task Gulp but aren't know how set the cookie variable previously (i know is a private function). The Gulp task request me of a way asynchrony the prompt requesting the cookie.

Change please in public the function that request the cookie.

**Comment by guilhermemarconi** [comment]
@jsiesquen actually there's no way to get the cookie dynamicaly because of the 2FA in VTEXID module. The prompt is required to input the authentication cookie value.
